version: '3'

services:
  client:
    build:
      context: ./frontend
      args:
        - REACT_APP_HOST_IP_ADDRESS=http://localhost:3001
    ports:
      - "3000:80"

  server:
    build: ./backend
    volumes:
      - json-data:/usr/src/app
    ports:
      - "3001:3001"

volumes:
  json-data:
    driver: local
